// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiVsZqSiLFXZF-tetK-pfFOZZ-sHPmrjc',
    appId: '1:517883933280:web:81d3160bfbf5779745c905',
    messagingSenderId: '517883933280',
    projectId: 'one-firebase-4266a',
    authDomain: 'one-firebase-4266a.firebaseapp.com',
    storageBucket: 'one-firebase-4266a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-ay_dC8xHzcTSq8LlGtsPjdUjfYBVx7E',
    appId: '1:517883933280:android:a5ea240cc471824845c905',
    messagingSenderId: '517883933280',
    projectId: 'one-firebase-4266a',
    storageBucket: 'one-firebase-4266a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX7JkzB7KK2PVQ8F8X09eUsOGw6XejZIg',
    appId: '1:517883933280:ios:9cea66954ce1cad045c905',
    messagingSenderId: '517883933280',
    projectId: 'one-firebase-4266a',
    storageBucket: 'one-firebase-4266a.appspot.com',
    iosClientId: '517883933280-ev3ckqpig654d3mk9vg7atp8ftmglacd.apps.googleusercontent.com',
    iosBundleId: 'com.kaibacorp.towers',
  );
}
